### ISSUE TITLE
Add apply for leave UI

### ISSUE THREAD

**Issue by elliottan** [CS2103-AY1819S1-F10-1/main#57]
- [x] View previously applied leaves and their statuses
- [x] Choose dates to apply for (normal input text box for now; future versions: calendar date picker)
- [x] Enter description of leave application

**Comment by elliottan** [comment]
- [ ] Check that dates chosen are not public holidays or weekends
