### ISSUE TITLE
Add LeaveApplication class into Model

### ISSUE THREAD

**Issue by elliottan** [CS2103-AY1819S1-F10-1/main#59]
LeaveApplication class that represents an application for leave from work.
- [x] Attributes include: ID, list of dates, description, status (enum), and Employee that applied for this leave.
API: methods to be confirmed.
- [x] Update Model class diagram to include this new LeaveApplication class and it's attributes
- [x] Add tests for LeaveApplication

**Comment by elliottan** [comment]
Also, update Model class diagram to include this new Leave class and it's attributes

**Comment by elliottan** [comment]
- [ ] Add tests for LeaveApplication
